### ISSUE TITLE
How to use it standalone?

### ISSUE THREAD

**Issue by kabeda** [silentmatt/expr-eval#115]
Hi,
Excuse me for my ignorance but what should I do for use this package as a script with jquery?

**Comment by silentmatt** [comment]
The built file uses the universal module definition pattern, so you can include it in your page with a normal script tag. It will expose a global named `exprEval` that has the `Parser` class as a property.

To get the script, you can either run `npm install expr-eval` to download it with npm, or you can grab the current version here: https://raw.githubusercontent.com/silentmatt/expr-eval/latest/dist/bundle.min.js

Then in your HTML:

    <script src="/path/to/bundle.min.js"></script>
    
    <script>
        var parser = new exprEval.Parser();
        console.log(parser.evaluate('x^2', { x: 5 }));
    </script>

Hope that helps to get you started. Let me know if you need any more info.

**Comment by kabeda** [comment]
Hi,
Thanks a lot. It was exprVal that I needed
