### ISSUE TITLE
Error if final char of string is whitespace

### ISSUE THREAD

**Issue by JheeBz** [silentmatt/expr-eval#123]
I'm using create-react-app to bootstrap my application and it uses Babel to parse the JSX into standard javascript. I've imported as per the instructions and instantiated a parser object as per below:
```javascript
const Parser = require('expr-eval').Parser;
```

Note this.state.currentCalculation will be an array of strings made up of numbers and arithmetic symbols (I use an x for multiplication in my UI but as you can see below I substibute with a * to times)
```javascript
        if (this.state.currentCalculation) {
          if (this.state.currentCalculation.length > 0) {
            const parser = new Parser()
            const expression = this.state.currentCalculation.map(calc => {
              return calc !== 'x' ? calc + ' ' : '* '
            })
            this.setState(() => ({
              currentCalculation: [],
              result: parser.parse(expression).evaluate,
              currentNumber: '0'
            }))
          }
```

But when I call the function I receive the following error:

```
TypeError: this.expression.charAt is not a function
TokenStream../node_modules/expr-eval/dist/bundle.js.TokenStream.isWhitespace
node_modules/expr-eval/dist/bundle.js:576
  573 | 
  574 | TokenStream.prototype.isWhitespace = function () {
  575 |   var r = false;
> 576 |   var c = this.expression.charAt(this.pos);
  577 |   while (c === ' ' || c === '\t' || c === '\n' || c === '\r') {
  578 |     r = true;
  579 |     this.pos++;
View compiled
TokenStream../node_modules/expr-eval/dist/bundle.js.TokenStream.next
node_modules/expr-eval/dist/bundle.js:447
  444 |   return this.newToken(TEOF, 'EOF');
  445 | }
  446 | 
> 447 | if (this.isWhitespace() || this.isComment()) {
  448 |   return this.next();
  449 | } else if (this.isRadixInteger() ||
  450 |     this.isNumber() ||
View compiled
ParserState../node_modules/expr-eval/dist/bundle.js.ParserState.next
node_modules/expr-eval/dist/bundle.js:889
  886 | 
  887 | ParserState.prototype.next = function () {
  888 |   this.current = this.nextToken;
> 889 |   return (this.nextToken = this.tokens.next());
  890 | };
  891 | 
  892 | ParserState.prototype.tokenMatches = function (token, value) {
View compiled
new ParserState
node_modules/expr-eval/dist/bundle.js:881
  878 | this.tokens = tokenStream;
  879 | this.current = null;
  880 | this.nextToken = null;
> 881 | this.next();
  882 | this.savedCurrent = null;
  883 | this.savedNextToken = null;
  884 | this.allowMemberAccess = options.allowMemberAccess !== false;
View compiled
Parser../node_modules/expr-eval/dist/bundle.js.Parser.parse
node_modules/expr-eval/dist/bundle.js:1418
  1415 | 
  1416 | Parser.prototype.parse = function (expr) {
  1417 |   var instr = [];
> 1418 |   var parserState = new ParserState(
  1419 |     this,
  1420 |     new TokenStream(this, expr),
  1421 |     { allowMemberAccess: this.options.allowMemberAccess }
View compiled
Calculator.<anonymous>
src/components/Calculator.jsx:62
  59 |   })
  60 |   this.setState(() => ({
  61 |     currentCalculation: [],
> 62 |     result: parser.parse(expression).evaluate,
  63 |     currentNumber: '0'
  64 |   }))
  65 | }
```

I've also tried to import it using the ES6 destructuring assignment and the import keyword:

`import { Parser } from 'expr-eval';`

I'm unsure if this is a genuine bug or just a funny issue with the way it works in React / Webpack.

**Comment by silentmatt** [comment]
The `parse` function assumes it will receive a string, and doesn't do any conversions for you if it's not, which I think is what's causing the problem.

Maybe try something like this:

    this.setState(() => ({
      currentCalculation: [],
      result: parser.parse(expression.join('')).evaluate(),
      currentNumber: '0'
    }))

Let me know if that helps.

**Comment by JheeBz** [comment]
Thanks for your swift reply. My tired self overlook the ```simple join(' ')``` solution which fixes the issue. The parameter was indeed a string (I type check it in my app). It the issue was a trailing space in my string.

This was definitely on me and should be the responsibility of the person inputting the value, but perhaps it would be good to trin any trailing whitespace?

**Comment by silentmatt** [comment]
Glad that helped! I'll think about ways to make it more resilient and/or make any errors it throws more helpful if there's nothing it can do about it.
