### ISSUE TITLE
Make arrays first class values

### ISSUE THREAD

**Issue by silentmatt** [silentmatt/expr-eval#125]
The only real support for arrays right now are the `in` operator, and the fact that they don't throw errors if you use them. They would be a lot more useful if you could create them in expressions and perform operations on them.

Definitely need:
- Indexing: array[0]
- Array literal syntax: [1, 2, 3]
- Function/property to get the length. Currently `array.length` is implicitly supported with object property access, but a function/operator that doesn't get disabled with property access would be useful.

Things to consider:
- Should trailing comma be allowed? Leaning toward no, but it can be convenient
- Should we support additional operations besides `in`? Concatenation?
- What comparison operators should be supported? <, > for lexical comparison? Or use native javascript behavior
- "Functional" operations like map, fold/reduce, filter, etc
- Should we apply operators element-wise to arrays? For example, [1, 2, 3] + [4, 5, 6] == [5, 7, 9]
- Matrix operations?

**Comment by marcato15** [comment]
Would this allow you to use arrays inside of functions like `min` or `max`? Also, would it be possible to  modify the `add` and `sum` methods to allow more than 2 parameters? I'd be happy to submit a PR.

I'm currently accomplishing passing in arrays as variables by doing this

```
const variables = {numbers: [0,1,2,3]};
min(array(numbers))".replace(/array\(([a-zA-Z0-9]*)\)/g,(v,o) => variables[o].join(","));```

**Comment by fbaligand** [comment]
Personally, I would love to just be able to get access to a array item in formula.

I mean:
```
const variables = { row: [0,1,2,3] };
const result = Parser.parse('row[1] * row[2]').evaluate(variables);
```

**Comment by Hirvesh** [comment]
Would love this feature, any progress on this? I'll love to help if possible!

**Comment by jeaneric** [comment]
At first, I struggled or think it was not possible to use array. But by using "Custom functions" that you define and use them in the parser. I'm able to do every thing I need. A little more work, but still not so complicated.

For example, a sum function:
```
sumarray(myarray){
    var total = 0;
    for(var i=0,n=myarray.length; i<n; ++i){
      if(myarray[i] && isNaN(myarray[i])===false){ //check if number
        total += +myarray[i]; // convert to number if string
      }
    }
    return total
  }
```

**Comment by Hirvesh** [comment]
@jeaneric What we mean here is to be able to refer to array keys/index in an expression and passing an array as variable.
