### ISSUE TITLE
`parser.d.ts` not published

### ISSUE THREAD

**Issue by andy-ms** [silentmatt/expr-eval#127]
The `package.json` contains `"typings": "parser.d.ts",` to indicate the presense of bundled typings, but it also contains [`"files": ["dist/"],`](https://docs.npmjs.com/files/package.json#files), which will prevent `parser.d.ts` from being published. I think all you need to do is add `parser.d.ts` to `files`.
(Also, I think the `.npmignore` is unnecessary if you explicitly specify "files".)

**Comment by silentmatt** [comment]
Thanks for pointing that out! I don't use TypeScript, so the type definitions have kind of been an afterthought.
