### ISSUE TITLE
Handle empty string in parse()

### ISSUE THREAD

**Issue by jarvisluong** [silentmatt/expr-eval#139]
Hi!

Is this a good idea that if an empty string is being passed into parse(), we evaluate it as 0?

**Comment by silentmatt** [comment]
Thanks for the suggestion. I would prefer leaving this up to the calling code though. Some users might want an empty string to be an error or evaluate to null, for example. Those would still work if we return 0, but throwing seems more explicit about it being your responsibility to decide how to handle it.
