### ISSUE TITLE
Typings of expression.substitute()

### ISSUE THREAD

**Issue by j2L4e** [silentmatt/expr-eval#150]
The typings of `expression.substitute()` are off.

At the moment it is 
```
substitute(values: Value): Expression;
```
which obviously isn't the actual behavior as the function expects 2 arguments.

I think it should be
```
substitute(propertyName: string, value: Expression | string | number): Expression;
```
but I haven't fully investigated this as I have little time right now.

**Comment by silentmatt** [comment]
You're right. I don't use TypeScript personally, and apparently didn't look at that closely enough.

**Comment by Gillardo** [comment]
is this published to npm, as i have just downloaded this library and i get this problem
