### ISSUE TITLE
versions 2.0.1 and 2.0.2 missing from changelog

### ISSUE THREAD

**Issue by harrysarson** [silentmatt/expr-eval#213]
Hi,

I was looking to update expr-eval to the latest version but noticed that there was no information about versions 2.0.1 or 2.0.2 in the changelog. Would it be possible to add this information?

(Please forgive me for being a lazy individual and not just reading the git history.)

Best

**Comment by silentmatt** [comment]
Thanks, for pointing that out. I've updated the changelog.

**Comment by harrysarson** [comment]
Thanks!
