### ISSUE TITLE
Using expr-eval on CodePen?

### ISSUE THREAD

**Issue by DragonOsman** [silentmatt/expr-eval#232]
I want to build a calculator app on CodePen for a FreeCodeCamp project challenge.  Is it possible to use expr-eval on CodePen?  And if so, how?  Thanks in advance for any help.

**Comment by DragonOsman** [comment]
Thanks for the reply and help.  I'll do that, then.

**Comment by silentmatt** [comment]
No problem. I'll close this, but feel free to re-open or open a new issue if you have problems or other questions.

**Comment by DragonOsman** [comment]
I do have another question about this.

What I want to do is build a calculator by following the specs mentioned [here](https://www.freecodecamp.org/learn/front-end-libraries/front-end-libraries-projects/build-a-javascript-calculator).  So my question is: is it possible to do this using this library for the calculation string parsing and evaluation?  It also says:

```
User Story #13: If 2 or more operators are entered consecutively, the operation performed should be the last operator entered (excluding the negative (-) sign). For example, if `5 + * 7` = is entered, the result should be `35` (i.e. 5 * 7); if 5 * - 5 = is entered, the result should be -25 (i.e. 5 x (-5)).
```
I'll be able to use this library for this, too, right?  Probably will have to write my own function, but yeah.

**Comment by silentmatt** [comment]
It won't be able to handle that directly, but you might be able to either pre-process the input to remove the extra operator before you evaluate it, or not append it in the first place if you're generating the string.

The way the parser's written, there probably isn't a good way to modify it to support that "natively" so you'll almost definitely need to do some kind of pre-processing.

**Comment by DragonOsman** [comment]
I don't have to completely ignore it, I actually need to use the operator given most recently.  And if I have something like "4 + - 5", it'll be treated as "4 + (-5)", probably.  Or "4 * - 5" -> "4 * -5".  Aside from that, when given consecutive operators, it has to take only the most recent one.
