### ISSUE TITLE
Error when a variable whose name starts with E or PI

### ISSUE THREAD

**Issue by omartrinidad** [silentmatt/expr-eval#33]
if a variable is defined with the names in upper-case and the names start with `E` or `PI` prefixes like `ERGONOMIC` or `PITTSBURGH`, the parser confuses them with the constants `Math.E` and `Math.PI` and throws the next error: `unexpected variable`.

**Comment by alexanderzeillinger** [comment]
Just had this problem as well, thanks for posting the reason.

**Comment by pierre-weceipt** [comment]
I had the same problem earlier, it seems to be solved with lowercased variables.
