### ISSUE TITLE
Add to CDNJS

### ISSUE THREAD

**Issue by silentmatt** [silentmatt/expr-eval#58]
It would help a lot of webmasters if you put your lib on [CDNJS](https://cdnjs.com/).

Split from #57 cc @johndoefromhere

**Comment by johndoefromhere** [comment]
@silentmatt Is it even meant to be used on websites? I'm getting an error on library load:

> Uncaught SyntaxError: Unexpected token export
> parser.js:1332

**Comment by silentmatt** [comment]
@johndoefromhere It should work in a browser, but you'll need to build it first, and use the bundled dist/bundle.js file. It's using the ES6 module syntax as a first step toward splitting it up into several modules to make it more manageable. Then rollup wraps it into a version that will work as a node module, AMD module, or as a global variable (`exprEval`).

If you have node/npm, you can either run `npm install expr-eval` and get the bundled file from that, or run `npm run build` in the project directory to build it yourself. Otherwise, you can either download it directly from https://registry.npmjs.org/expr-eval/-/expr-eval-0.12.0.tgz or email me, and I can send you the bundled file.

**Comment by kamil-i2a** [comment]
@silentmatt Great, thanks for quick answer. Could you include your whole dist folder in your repo? As far as I know you need to do it to make it hosted on cdnjs.

**Comment by johndoefromhere** [comment]
@silentmatt Any update on this? :)

**Comment by silentmatt** [comment]
I'm hoping to get the 1.0.0 release out soon (possibly today), then this will be one of the next things I work on.

**Comment by silentmatt** [comment]
It looks like someone beat me to it. For reference: https://github.com/extend1994/cdnjs/commit/f5fffba233333a97c1754d09f8f5d9d358fc3daf
