### ISSUE TITLE
Operators taking precedence even within variable names

### ISSUE THREAD

**Issue by doublemarked** [silentmatt/expr-eval#61]
It seems that the parser is giving precedence to operators found within variable names, which feels like a bug. For example, the following will fail to parse because it is matching `or` within the variable name:

```
   Parser.evaluate('org > 5', { org: 10 })
```

It feels like the parser should be observing word boundaries, or maybe that variables should be parsed out before operators?

**Comment by silentmatt** [comment]
Yup, that's definitely a bug, thanks!

**Comment by doublemarked** [comment]
Thank you very much, and so quickly no less! :)
