### ISSUE TITLE
Add support for variable assignment

### ISSUE THREAD

**Issue by silentmatt** [silentmatt/expr-eval#65]
Right now "variables" are really constants that are evaluated at evaluation time, instead of parse time. I should consider adding an assignment operator (probably either `=` or `:=`).

Some considerations:
- There's no concept of "statements" so it's somewhat questionable if there's a real use case for this.
  - But maybe a statement/expression separator could be added (like the `,` operator in JavaScript), to allow expressions like `x = random(); x * x` which would only be possible now by evaluating `x` ahead of time and passing it in as an argument.
- Currently, expression evaluation is essentially side-effect free (with the minor exception of random, which updates the current PRNG state).
- Support could be made opt-in with the new options argument.

**Comment by desnet** [comment]
please update the package in the npm repository with assignment support

**Comment by silentmatt** [comment]
@desnet FYI, this is in the new 2.0.0 release.
