### ISSUE TITLE
Parser Bug with comparison operator

### ISSUE THREAD

**Issue by germanjoey** [silentmatt/expr-eval#89]
Howdy,

I believe I've found a small bug in your parser here:

![Bug Screenshot](http://i.imgur.com/2zxvJR2.jpg "Bug Screenshot")

Somehow the '-' sign in the expression gets transformed into a '+' in the tokens. Any ideas on how to fix this sucker?

Thanks,
Joey

**Comment by germanjoey** [comment]
Hmmm, a real head-scratcher here. Somehow the bug has cleared up on its own after a page refresh. I wonder if some sort of internal state in the parser was corrupted after parsing some sort of prior expression? Any ideas?

**Comment by silentmatt** [comment]
That's a really weird one. You're probably right about some internal state getting corrupted at some point. Do you remember if you had used the simplify method before this?

**Comment by germanjoey** [comment]
I'm fairly certain that I did not, as I was playing around in the command line debugging another function that I fed the output tokens into. I was repeatedly using the same parser, if that's helpful to know at all.

Thanks for taking a look at this.

**Comment by silentmatt** [comment]
I just pushed out a new version (1.0.1) which removes some caching that doesn't seem to really help performance anyway, and is most likely at least part of the problem that caused this.

**Comment by germanjoey** [comment]
Thanks a lot for the quick response! I'll let you know if I ever encounter the problem again.
