### ISSUE TITLE
Variable name confusion

### ISSUE THREAD

**Issue by rubenstolk** [silentmatt/expr-eval#93]
Hi, I want to use this library for an app where users can define their own variable names and formulas. Now the issue is that someone might define a variable with the name `max` and try to use it in a formula.

Because `max` is also a predefined function, this isn't going to work.

Perhaps there should be a better way to distinguish between whether something is a variable or a function?

**Comment by silentmatt** [comment]
That's a good point. There should be a way to either distinguish them, or let variable names override built-ins. The support for variables and functions was originally very simplistic, and I haven't changed it much along the way, so it could definitely use some attention.

I'm considering adding real support for variables (for example, declaring/assigning to them in the expression), but I haven't worked out the details yet. Fixing this would probably be a part of that process.

**Comment by silentmatt** [comment]
One way of dealing with the issue right now would be to remove the built-in functions and add them back in as variables. That would strip away their "privileged" status, and cause them to behave like any other variable.

As an example:

    var parser = new Parser();
    var builtInFunctions = parser.functions;
    parser.functions = {};
    var scope = Object.create(builtInFunctions); // Object.create is optional, I'm just doing it here to essentially create a child scope
    scope.max = 42;
    console.log(parser.parse('2 * max').evaluate(scope)); // => 84

**Comment by rubenstolk** [comment]
FYI:

I've taken a different workaround for my app:
- I've declared all values as `name_`, so it would be `max_`
- I'm letting users use variables prefixed with `$` and then I simply replace the formula (```formula.replace(/\$([A-Za-z0-9_]+)/g, '$1_')``` before using it in exprEval

Perhaps supporting `$var` natively would solve the issue...

**Comment by silentmatt** [comment]
That's actually a good idea. Adding native support for $var would be pretty easy too without breaking backward compatibility, so I could include that in the 1.1.0 release.

**Comment by rubenstolk** [comment]
Good to hear, thanks @silentmatt!
